import './styles/globals.css'
import './styles/Home.module.css'
import '../public/css/preloader.css'
import '../public/css/backToTop.css'
import '../public/css/fontAwesome5Pro.css'
import '../public/css/elegantFont.css'
import '../public/css/style.css'
import '../public/css/animate.min.css'
import '../public/css/default.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
